### ISSUE TITLE
wtf is going on here!

### ISSUE THREAD

**Issue by jamieduk** [teqneers/shamir#11]
$shares = Secret::share('Shamir\'s Shared Secret Implementation in PHP', 5, 2);  should be

$shares = Secret::share("Shamir's Shared Secret Implementation in PHP', 5, 2");

you need to put files into includes not use vender library crap! this is a bs way of doing php in my opinion and all these files are just crap i expect 1 or 2 files not a load of files!!!

**Comment by butimo** [comment]
Jay, same here. Don't use it, if you don't like it. Nobody forces you to do so.
