### ISSUE TITLE
Can we have a stable release on Packagist?

### ISSUE THREAD

**Issue by marclaporte** [teqneers/shamir#17]
We use lib in Tiki:
https://doc.tiki.org/Shared-Secrets

And I'd like to use a stable version, at least for our LTS version.

Thanks!

**Comment by marclaporte** [comment]
Thank you for version 2.0!
https://packagist.org/packages/teqneers/shamir#2.0.0

**Comment by ogmueller** [comment]
Sorry, for the delay.
