### ISSUE TITLE
teqneers/shamir on Packagist.org

### ISSUE THREAD

**Issue by marclaporte** [teqneers/shamir#6]
It would be nice to have available like the others:
https://packagist.org/packages/teqneers/

Thanks!

**Comment by sgehrig** [comment]
Hi @marclaporte,

sure - no problem. Sorry that we missed that.

https://packagist.org/packages/tq/shamir

**Comment by marclaporte** [comment]
Thank you!

P.S. Here is updated URL: https://packagist.org/packages/teqneers/shamir
