### ISSUE TITLE
is this binary safe, and if yes, could one input the secret in a format like bas64

### ISSUE THREAD

**Issue by My1** [teqneers/shamir#8]
that could allow for not having to encode the secret into character sets which if the characters are encoded byte by byte anyway, that one could make the secrets shorter which would definitely be nice

**Comment by ogmueller** [comment]
Yes, shamir is using a binary safe way to encode the secret. Your input is read using PHP function [unpack](https://www.php.net/manual/en/function.unpack.php).

So you can use binary data or base64.

**Comment by My1** [comment]
cool although binary data would be hard to use on the console, lol

which I thought it might be useful to decode base64 to binary before doing the algo

**Comment by ogmueller** [comment]
Good point! I've just added a file option (-f) and a STDIN pipe. Try it out.

```
# echo -n "Share my secret" | bin/shamir.php shamir:share

  102014k3:4:371u0i042i0p343t1i0h1l55
  102021f5h1,3z14043l250i3s520r3*0v1*
  102033*194n4i0n5m161,0b470x5n1z5s4l
  
# bin/shamir.php shamir:share -f path/to/secretFile

  10201010-2p4+1:1c4947512b2-194,2,4*
  102023+582#1q1k1,0c5s3s1*3o091i3i1q
  10203243y3g3#122h221h2a1s484+3v3%3*
```

**Comment by My1** [comment]
cool. just need to find a decent way to get it output as b64 since the place where I wanna use it is NOT supposed to store the secret anywhere :-)

input seems to work tho.
```
echo -n testtesttest | base64 -d | phpfun/shamir-master/bin/shamir.php shamir:share -s 4 -t 3
```
(yes testtesttest is valid base64)

for output tho it seems I cant just go pipe it to base64...
